// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ioNennTAAaH7RnvF0B76dCbZVga550w',
    appId: '1:911288213854:web:d423b4aeb7a77d62f6afcf',
    messagingSenderId: '911288213854',
    projectId: 'kidsgrowth-cde91',
    authDomain: 'kidsgrowth-cde91.firebaseapp.com',
    storageBucket: 'kidsgrowth-cde91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdRg9FxMm3b3WM6tNDfE5fYVXekE4nIg',
    appId: '1:911288213854:android:d496797504e6ccb2f6afcf',
    messagingSenderId: '911288213854',
    projectId: 'kidsgrowth-cde91',
    storageBucket: 'kidsgrowth-cde91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fbgH37Y-J_9YVGAYAolLy-uLtRftMEE',
    appId: '1:911288213854:ios:cebce33ff0fb2b06f6afcf',
    messagingSenderId: '911288213854',
    projectId: 'kidsgrowth-cde91',
    storageBucket: 'kidsgrowth-cde91.firebasestorage.app',
    iosBundleId: 'com.garpoo.kidsGrowthPlus',
  );
}
